// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANpP58unbGK8HSv9HumdEpopaxMB0Unxk',
    appId: '1:892525529:web:6a450df2c5273ad56717c8',
    messagingSenderId: '892525529',
    projectId: 'igcare',
    authDomain: 'igcare.firebaseapp.com',
    storageBucket: 'igcare.firebasestorage.app',
    measurementId: 'G-DHFX6307KX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOxNSHVRVOU1NN-QlSbkqjAwTcf7RVMhk',
    appId: '1:892525529:android:dfff602f6d400d446717c8',
    messagingSenderId: '892525529',
    projectId: 'igcare',
    storageBucket: 'igcare.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcIxyvTTS5ZK1v44Rv7lVLtVAXi-SW0I8',
    appId: '1:892525529:ios:576a82691737536b6717c8',
    messagingSenderId: '892525529',
    projectId: 'igcare',
    storageBucket: 'igcare.firebasestorage.app',
    iosBundleId: 'com.example.igCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcIxyvTTS5ZK1v44Rv7lVLtVAXi-SW0I8',
    appId: '1:892525529:ios:576a82691737536b6717c8',
    messagingSenderId: '892525529',
    projectId: 'igcare',
    storageBucket: 'igcare.firebasestorage.app',
    iosBundleId: 'com.example.igCare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANpP58unbGK8HSv9HumdEpopaxMB0Unxk',
    appId: '1:892525529:web:5716edd7c254e3306717c8',
    messagingSenderId: '892525529',
    projectId: 'igcare',
    authDomain: 'igcare.firebaseapp.com',
    storageBucket: 'igcare.firebasestorage.app',
    measurementId: 'G-1SMTTEJKT9',
  );

}